// 用于加载controller和service类
import '../service/admin.service'
import '../service/pe.service'
import '../service/topic.service'
import '../service/video.service'
import '../service/banner.service'
import '../service/user.service'
import '../service/order.service'
import '../service/income_stat.service'
import '../service/project.service'
import '../service/income_detail.service'
import '../service/person_income.service'

import '../controller/app.controller'
import '../controller/login.controller'
import '../controller/admin.controller'
import '../controller/menu.controller'
import '../controller/welcome.controller'
import '../controller/pe.controller'
import '../controller/topic.controller'
import '../controller/video.controller'
import '../controller/banner.controller'
import '../controller/user.controller'
import '../controller/order.controller'
import '../controller/income_stat.controller'
import '../controller/project.controller'
import '../controller/income_detail.controller'
import '../controller/person_income.controller'

import '../filters/date.filter'

import '../directives/date.converter'
